jobs: 100
use-conda: true
conda-frontend: mamba
use-singularity: true
default-resources: [cpus=1, mem_mb=16000, time_min=120, heavy_network=0]
resources: [cpus=92, mem_mb=160000, heavy_network=1]
latency-wait: 60
singularity-args: "--home /home/$USER:/home/$USER --bind /geomicro:/geomicro"